import { Question, LeaderboardEntry, Subject } from './types';

export const SUBJECTS: Subject[] = ['General Knowledge', 'Science', 'History', 'Technology'];

export const FFF_QUESTION: Question = {
  id: 'fff-1',
  text: 'Arrange these units of time in ascending order (Shortest to Longest):',
  options: ['Minute', 'Millisecond', 'Hour', 'Second'], // Jumbled
  correctAnswer: '', // Not used for FFF in new logic
  correctOrder: ['Millisecond', 'Second', 'Minute', 'Hour'],
  difficulty: 'easy',
  hint: 'Think about physics.',
};

// Real Question Bank
export const QUESTIONS_DB: Record<Subject, Question[]> = {
  'General Knowledge': [
    {
      id: 'gk-1',
      text: 'Which is the largest ocean on Earth?',
      options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
      correctAnswer: 'Pacific Ocean',
      difficulty: 'easy',
      hint: 'It covers more than 30% of the Earth’s surface.',
    },
    {
      id: 'gk-2',
      text: 'Who wrote "Romeo and Juliet"?',
      options: ['Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen'],
      correctAnswer: 'William Shakespeare',
      difficulty: 'easy',
      hint: 'He was an English playwright and poet.',
    },
    {
      id: 'gk-3',
      text: 'What represents the letter "O" in the periodic table?',
      options: ['Osmium', 'Oxygen', 'Oganesson', 'Oxide'],
      correctAnswer: 'Oxygen',
      difficulty: 'easy',
      hint: 'It is essential for respiration.',
    },
    {
      id: 'gk-4',
      text: 'Which country is known as the Land of the Rising Sun?',
      options: ['China', 'South Korea', 'Japan', 'Thailand'],
      correctAnswer: 'Japan',
      difficulty: 'easy',
      hint: 'It is an island nation in East Asia.',
    },
    {
      id: 'gk-5',
      text: 'What is the currency of the United Kingdom?',
      options: ['Euro', 'Dollar', 'Pound Sterling', 'Franc'],
      correctAnswer: 'Pound Sterling',
      difficulty: 'medium',
      hint: 'It is one of the oldest currencies still in use.',
    },
    {
      id: 'gk-6',
      text: 'In which sport would you perform a slam dunk?',
      options: ['Volleyball', 'Tennis', 'Basketball', 'Soccer'],
      correctAnswer: 'Basketball',
      difficulty: 'medium',
      hint: 'It involves a hoop.',
    },
    {
      id: 'gk-7',
      text: 'Which planet is known as the Red Planet?',
      options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
      correctAnswer: 'Mars',
      difficulty: 'medium',
      hint: 'It is the fourth planet from the Sun.',
    },
    {
      id: 'gk-8',
      text: 'Who painted the Mona Lisa?',
      options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet'],
      correctAnswer: 'Leonardo da Vinci',
      difficulty: 'hard',
      hint: 'He was a quintessential Renaissance man.',
    },
    {
      id: 'gk-9',
      text: 'What is the hardest natural substance on Earth?',
      options: ['Gold', 'Iron', 'Diamond', 'Platinum'],
      correctAnswer: 'Diamond',
      difficulty: 'hard',
      hint: 'It is made of carbon atoms arranged in a crystal lattice.',
    },
    {
      id: 'gk-10',
      text: 'Which organ in the human body is primarily responsible for filtering blood?',
      options: ['Heart', 'Liver', 'Kidneys', 'Lungs'],
      correctAnswer: 'Kidneys',
      difficulty: 'hard',
      hint: 'Humans typically have two of these bean-shaped organs.',
    },
    {
      id: 'gk-11',
      text: 'What is the capital city of Australia?',
      options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
      correctAnswer: 'Canberra',
      difficulty: 'hard',
      hint: 'It is an inland city, not on the coast like Sydney.',
    },
    {
      id: 'gk-12',
      text: 'Which gas makes up the majority of Earth\'s atmosphere?',
      options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
      correctAnswer: 'Nitrogen',
      difficulty: 'hard',
      hint: 'It makes up about 78% of the atmosphere.',
    },
    {
      id: 'gk-13',
      text: 'Who was the first person to step on the Moon?',
      options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'Michael Collins'],
      correctAnswer: 'Neil Armstrong',
      difficulty: 'hard',
      hint: 'He said "That\'s one small step for man..."',
    },
    {
      id: 'gk-14',
      text: 'What is the smallest country in the world by land area?',
      options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
      correctAnswer: 'Vatican City',
      difficulty: 'hard',
      hint: 'It is an enclave within Rome.',
    },
    {
      id: 'gk-15',
      text: 'Which chemical element has the symbol "Au"?',
      options: ['Silver', 'Gold', 'Copper', 'Aluminum'],
      correctAnswer: 'Gold',
      difficulty: 'hard',
      hint: 'It is a precious yellow metal.',
    }
  ],
  'Science': [
    {
      id: 'sci-1',
      text: 'What is the chemical symbol for water?',
      options: ['H2O', 'CO2', 'O2', 'NaCl'],
      correctAnswer: 'H2O',
      difficulty: 'easy',
      hint: 'Two hydrogen atoms and one oxygen atom.',
    },
    {
      id: 'sci-2',
      text: 'Which planet is closest to the Sun?',
      options: ['Venus', 'Earth', 'Mercury', 'Mars'],
      correctAnswer: 'Mercury',
      difficulty: 'easy',
      hint: 'It is the smallest planet in the Solar System.',
    },
    {
      id: 'sci-3',
      text: 'What gas do plants absorb from the atmosphere for photosynthesis?',
      options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'],
      correctAnswer: 'Carbon Dioxide',
      difficulty: 'easy',
      hint: 'Animals exhale this gas.',
    },
    {
      id: 'sci-4',
      text: 'What represents the "powerhouse" of the cell?',
      options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Cytoplasm'],
      correctAnswer: 'Mitochondria',
      difficulty: 'easy',
      hint: 'It generates most of the chemical energy needed to power the cell.',
    },
    {
      id: 'sci-5',
      text: 'What is the speed of light in vacuum (approx)?',
      options: ['300,000 km/s', '150,000 km/s', '1,000 km/s', '3,000,000 km/s'],
      correctAnswer: '300,000 km/s',
      difficulty: 'medium',
      hint: 'It is the universal speed limit.',
    },
    {
      id: 'sci-6',
      text: 'Which blood type is known as the universal donor?',
      options: ['Type A', 'Type B', 'Type AB', 'Type O Negative'],
      correctAnswer: 'Type O Negative',
      difficulty: 'medium',
      hint: 'This blood type lacks A, B, and Rh antigens.',
    },
    {
      id: 'sci-7',
      text: 'What is the most abundant gas in the universe?',
      options: ['Helium', 'Oxygen', 'Hydrogen', 'Carbon'],
      correctAnswer: 'Hydrogen',
      difficulty: 'medium',
      hint: 'It is the lightest element.',
    },
    {
      id: 'sci-8',
      text: 'Who proposed the theory of relativity?',
      options: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla'],
      correctAnswer: 'Albert Einstein',
      difficulty: 'hard',
      hint: 'E = mc^2',
    },
    {
      id: 'sci-9',
      text: 'What is the study of fungi called?',
      options: ['Botany', 'Mycology', 'Virology', 'Zoology'],
      correctAnswer: 'Mycology',
      difficulty: 'hard',
      hint: 'Mushrooms and molds fall under this field.',
    },
    {
      id: 'sci-10',
      text: 'Which particle has a negative charge?',
      options: ['Proton', 'Neutron', 'Electron', 'Photon'],
      correctAnswer: 'Electron',
      difficulty: 'hard',
      hint: 'It orbits the nucleus of an atom.',
    },
    {
      id: 'sci-11',
      text: 'What is the pH level of pure water?',
      options: ['5', '7', '9', '0'],
      correctAnswer: '7',
      difficulty: 'hard',
      hint: 'It is considered neutral.',
    },
    {
      id: 'sci-12',
      text: 'Which planet has the most moons?',
      options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
      correctAnswer: 'Saturn',
      difficulty: 'hard',
      hint: 'It is famous for its extensive ring system.',
    },
    {
      id: 'sci-13',
      text: 'What is the main metal found in the Earth\'s core?',
      options: ['Gold', 'Lead', 'Iron', 'Aluminum'],
      correctAnswer: 'Iron',
      difficulty: 'hard',
      hint: 'It is magnetic.',
    },
    {
      id: 'sci-14',
      text: 'What is the unit of electrical resistance?',
      options: ['Volt', 'Ampere', 'Ohm', 'Watt'],
      correctAnswer: 'Ohm',
      difficulty: 'hard',
      hint: 'Named after a German physicist.',
    },
    {
      id: 'sci-15',
      text: 'Which vitamin is produced by the skin when exposed to sunlight?',
      options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'],
      correctAnswer: 'Vitamin D',
      difficulty: 'hard',
      hint: 'It helps regulate calcium.',
    }
  ],
  'History': [
    {
      id: 'hist-1',
      text: 'Who was the first President of the United States?',
      options: ['Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'John Adams'],
      correctAnswer: 'George Washington',
      difficulty: 'easy',
      hint: 'He is on the one-dollar bill.',
    },
    {
      id: 'hist-2',
      text: 'In which year did World War II end?',
      options: ['1945', '1939', '1918', '1965'],
      correctAnswer: '1945',
      difficulty: 'easy',
      hint: 'It ended shortly after the atomic bombings.',
    },
    {
      id: 'hist-3',
      text: 'Which ancient civilization built the Pyramids?',
      options: ['Romans', 'Greeks', 'Egyptians', 'Mayans'],
      correctAnswer: 'Egyptians',
      difficulty: 'easy',
      hint: 'They lived along the Nile River.',
    },
    {
      id: 'hist-4',
      text: 'Who discovered America in 1492?',
      options: ['Christopher Columbus', 'Vasco da Gama', 'Ferdinand Magellan', 'Marco Polo'],
      correctAnswer: 'Christopher Columbus',
      difficulty: 'easy',
      hint: 'He sailed the Ocean Blue.',
    },
    {
      id: 'hist-5',
      text: 'Which ship sank in 1912 after hitting an iceberg?',
      options: ['Lusitania', 'Titanic', 'Britannic', 'Olympic'],
      correctAnswer: 'Titanic',
      difficulty: 'medium',
      hint: 'It was called "unsinkable".',
    },
    {
      id: 'hist-6',
      text: 'Who was the French military leader who declared himself Emperor?',
      options: ['Louis XVI', 'Charlemagne', 'Napoleon Bonaparte', 'Robespierre'],
      correctAnswer: 'Napoleon Bonaparte',
      difficulty: 'medium',
      hint: 'He was defeated at Waterloo.',
    },
    {
      id: 'hist-7',
      text: 'Which wall fell in 1989, symbolizing the end of the Cold War?',
      options: ['Great Wall of China', 'Berlin Wall', 'Hadrian\'s Wall', 'Western Wall'],
      correctAnswer: 'Berlin Wall',
      difficulty: 'medium',
      hint: 'It divided a German city.',
    },
    {
      id: 'hist-8',
      text: 'Who was the first female Prime Minister of the UK?',
      options: ['Theresa May', 'Margaret Thatcher', 'Queen Elizabeth II', 'Indira Gandhi'],
      correctAnswer: 'Margaret Thatcher',
      difficulty: 'hard',
      hint: 'She was known as the "Iron Lady".',
    },
    {
      id: 'hist-9',
      text: 'Which empire was ruled by Genghis Khan?',
      options: ['Roman Empire', 'Ottoman Empire', 'Mongol Empire', 'British Empire'],
      correctAnswer: 'Mongol Empire',
      difficulty: 'hard',
      hint: 'It was the largest contiguous land empire in history.',
    },
    {
      id: 'hist-10',
      text: 'In which year did the French Revolution begin?',
      options: ['1776', '1789', '1812', '1492'],
      correctAnswer: '1789',
      difficulty: 'hard',
      hint: 'The same year the US Constitution came into effect.',
    },
    {
      id: 'hist-11',
      text: 'Who was assassinated in Sarajevo, sparking World War I?',
      options: ['Archduke Franz Ferdinand', 'Kaiser Wilhelm II', 'Tsar Nicholas II', 'Gavrilo Princip'],
      correctAnswer: 'Archduke Franz Ferdinand',
      difficulty: 'hard',
      hint: 'He was the heir to the Austro-Hungarian throne.',
    },
    {
      id: 'hist-12',
      text: 'Which civilization is known for the Machu Picchu ruins?',
      options: ['Aztec', 'Inca', 'Maya', 'Olmec'],
      correctAnswer: 'Inca',
      difficulty: 'hard',
      hint: 'Located in modern-day Peru.',
    },
    {
      id: 'hist-13',
      text: 'Who wrote the Declaration of Independence?',
      options: ['George Washington', 'Benjamin Franklin', 'Thomas Jefferson', 'John Hancock'],
      correctAnswer: 'Thomas Jefferson',
      difficulty: 'hard',
      hint: 'He was the third US President.',
    },
    {
      id: 'hist-14',
      text: 'The Battle of Hastings took place in which year?',
      options: ['1066', '1215', '1492', '1776'],
      correctAnswer: '1066',
      difficulty: 'hard',
      hint: 'William the Conqueror defeated King Harold II.',
    },
    {
      id: 'hist-15',
      text: 'Which country was formerly known as Ceylon?',
      options: ['India', 'Sri Lanka', 'Thailand', 'Myanmar'],
      correctAnswer: 'Sri Lanka',
      difficulty: 'hard',
      hint: 'It is an island nation south of India.',
    }
  ],
  'Technology': [
    {
      id: 'tech-1',
      text: 'What does "CPU" stand for?',
      options: ['Central Process Unit', 'Central Processing Unit', 'Computer Personal Unit', 'Central Processor Utility'],
      correctAnswer: 'Central Processing Unit',
      difficulty: 'easy',
      hint: 'It is the brain of the computer.',
    },
    {
      id: 'tech-2',
      text: 'Which company developed the iPhone?',
      options: ['Samsung', 'Microsoft', 'Google', 'Apple'],
      correctAnswer: 'Apple',
      difficulty: 'easy',
      hint: 'Founded by Steve Jobs.',
    },
    {
      id: 'tech-3',
      text: 'What is the main function of RAM in a computer?',
      options: ['Permanent storage', 'Cooling the system', 'Temporary data storage', 'Power supply'],
      correctAnswer: 'Temporary data storage',
      difficulty: 'easy',
      hint: 'It is volatile memory.',
    },
    {
      id: 'tech-4',
      text: 'What does "www" stand for in a website browser?',
      options: ['World Wide Web', 'World Web Wide', 'Wide World Web', 'Web World Wide'],
      correctAnswer: 'World Wide Web',
      difficulty: 'easy',
      hint: 'Tim Berners-Lee invented it.',
    },
    {
      id: 'tech-5',
      text: 'Which programming language is primarily used for web development alongside HTML and CSS?',
      options: ['Python', 'Java', 'JavaScript', 'C++'],
      correctAnswer: 'JavaScript',
      difficulty: 'medium',
      hint: 'It makes websites interactive.',
    },
    {
      id: 'tech-6',
      text: 'What is the name of the operating system developed by Google for mobile devices?',
      options: ['iOS', 'Windows Mobile', 'Android', 'Symbian'],
      correctAnswer: 'Android',
      difficulty: 'medium',
      hint: 'It is named after a robot.',
    },
    {
      id: 'tech-7',
      text: 'Who is the founder of Microsoft?',
      options: ['Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Elon Musk'],
      correctAnswer: 'Bill Gates',
      difficulty: 'medium',
      hint: 'He is also a philanthropist.',
    },
    {
      id: 'tech-8',
      text: 'What does "HTTP" stand for?',
      options: ['HyperText Transfer Protocol', 'HyperText Transmission Process', 'HyperText Transfer Product', 'HyperText Type Protocol'],
      correctAnswer: 'HyperText Transfer Protocol',
      difficulty: 'hard',
      hint: 'The foundation of data communication on the web.',
    },
    {
      id: 'tech-9',
      text: 'In computing, what is the term for a "zombie" computer utilized in a botnet?',
      options: ['Bot', 'Drone', 'Clone', 'Spectre'],
      correctAnswer: 'Bot',
      difficulty: 'hard',
      hint: 'Short for robot.',
    },
    {
      id: 'tech-10',
      text: 'Which technology is used to make telephone calls over the Internet?',
      options: ['VoIP', 'Bluetooth', 'Wi-Fi', 'Ethernet'],
      correctAnswer: 'VoIP',
      difficulty: 'hard',
      hint: 'Voice over Internet Protocol.',
    },
    {
      id: 'tech-11',
      text: 'What was the first computer virus called?',
      options: ['Creeper', 'ILOVEYOU', 'Melissa', 'MyDoom'],
      correctAnswer: 'Creeper',
      difficulty: 'hard',
      hint: 'It was created in 1971.',
    },
    {
      id: 'tech-12',
      text: 'What does "GPU" stand for?',
      options: ['General Processing Unit', 'Graphics Processing Unit', 'Graphical Performance Utility', 'Global Positioning Unit'],
      correctAnswer: 'Graphics Processing Unit',
      difficulty: 'hard',
      hint: 'Essential for gaming and rendering.',
    },
    {
      id: 'tech-13',
      text: 'Which company owns GitHub?',
      options: ['Google', 'Amazon', 'Microsoft', 'Facebook'],
      correctAnswer: 'Microsoft',
      difficulty: 'hard',
      hint: 'Acquired in 2018.',
    },
    {
      id: 'tech-14',
      text: 'What is the smallest unit of digital information?',
      options: ['Byte', 'Bit', 'Nibble', 'Pixel'],
      correctAnswer: 'Bit',
      difficulty: 'hard',
      hint: 'Binary digit (0 or 1).',
    },
    {
      id: 'tech-15',
      text: 'Which year was the first iPhone released?',
      options: ['2005', '2007', '2009', '2010'],
      correctAnswer: '2007',
      difficulty: 'hard',
      hint: 'Introduced by Steve Jobs.',
    }
  ]
};


export const LEADERBOARD_DATA: LeaderboardEntry[] = [
  { rank: 1, name: 'Sujal Kalal', subject: 'Technology', status: 'Completed', date: '2025-01-15' },
  { rank: 2, name: 'Alice Smith', subject: 'Science', status: 'Reached Q11', date: '2025-02-10' },
  { rank: 3, name: 'John Doe', subject: 'History', status: 'Reached Q10', date: '2025-02-12' },
  { rank: 4, name: 'Emma Brown', subject: 'General Knowledge', status: 'Reached Q9', date: '2025-02-14' },
  { rank: 5, name: 'Michael Lee', subject: 'Technology', status: 'Reached Q8', date: '2025-02-14' },
];

export const TIMER_RULES = {
  Q1_4: 15,
  Q5_7: 30,
  Q8_9: 60,
  Q10_12: Infinity,
};